---

- name: Add OpenVPN repo GPG key
  apt_key:
    id: E158C569
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
  when: openvpn_use_external_repo

- name: Add OpenVPN repo sources
  apt_repository:
    filename: openvpn
    repo: deb http://swupdate.openvpn.net/apt {{ ansible_lsb.codename }} main
  when: openvpn_use_external_repo

- name: Install requirements (Debian)
  apt:
    name: [openvpn, udev, openssl, zip]
    force: yes

- name: Install dependencies (Debian)
  apt:
    name: [libpam-pwdfile, python-passlib]
    force: yes
  when: openvpn_use_pam_users|default(false)

- name: Install easy-rsa package
  apt: name=easy-rsa
  when: openvpn_use_system_easyrsa

- name: Install LDAP dependencies (Debian)
  apt: name=openvpn-auth-ldap force=yes
  when: openvpn_use_ldap

- name: Install bridge dependencies (Debian)
  apt:
    name: [bridge-utils]
  when: openvpn_bridge
